support for read only /boot mount
Support is added for greenboot to work with read-only /boot.
It uses PrivateMounts=yes to isolate the system and remounts
boot as rw followed by setting the grub parameters as per healthcheck.

The following services are affected:

greenboot-grub2-set-success.service
greenboot-grub2-set-counter.service
greenboot-rpm-ostree-check-fallback.service

The grub2-editenv command is decoupled from greenboot-grub2-set-success.service
and is part of a separate script.

Signed-off-by: saypaul <paul.sayan@gmail.com>

diff --git a/usr/libexec/greenboot/greenboot-rpm-ostree-grub2-check-fallback b/usr/libexec/greenboot/greenboot-rpm-ostree-grub2-check-fallback
--- a/usr/libexec/greenboot/greenboot-rpm-ostree-grub2-check-fallback
+++ b/usr/libexec/greenboot/greenboot-rpm-ostree-grub2-check-fallback
@@ -1,6 +1,8 @@
 #!/bin/bash
 set -euo pipefail
 
+source /usr/libexec/greenboot/greenboot-boot-remount
+
 # Determine if the current boot is a fallback boot
 # If booted into fallback deployment, clean up bootloader entries (rollback)
 if grub2-editenv list | grep -q "^boot_counter=-1$"; then
@@ -12,5 +14,15 @@ if grub2-editenv list | grep -q "^boot_counter=-1$"; then
     echo "<3>Health check logs from previous boot:"
     echo "<3>$prev_logs"
   fi
-  grub2-editenv - unset boot_counter
+
+remount_boot_rw
+
+  if ! /usr/bin/grub2-editenv - unset boot_counter; then
+    # If the above command fails, remount /boot as read-only and exit with failure
+    remount_boot_ro
+    exit 1
+  fi
 fi
+
+# Remount /boot as read-only if it was mounted as read-write
+remount_boot_ro
